---
project_name: s3-substring-finder

env:
  - CGO_ENABLED=0
  - GO111MODULE=auto

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: binary
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    binary: s3-substring-finder
    ldflags:
      - -s -w -X github.com/bilalcaliskan/s3-substring-finder/cmd.GitVersion={{ .Version }} -X github.com/bilalcaliskan/s3-substring-finder/cmd.gitCommit={{ .ShortCommit }}  -X github.com/bilalcaliskan/s3-substring-finder/cmd.buildDate={{ .CommitDate }}
    main: ./main.go

archives:
  - replacements:
      amd64: x86_64

release:
  github:
    owner: bilalcaliskan
    name: s3-substring-finder

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^build:'
      - 'README'
      - '^Merge branch'
      - '^Merge pull request'
